# Generated by Django 2.2.6 on 2019-10-13 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
                ('is_lost', models.BooleanField(default=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lng', models.CharField(default=None, max_length=50)),
                ('lat', models.CharField(default=None, max_length=50)),
                ('login', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('identity', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
