# Generated by Django 2.2.6 on 2019-10-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thing',
            name='category',
            field=models.CharField(default='other', max_length=50),
        ),
    ]
