# Generated by Django 2.2.6 on 2019-10-13 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191012_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localisation',
            name='things',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.Thing'),
        ),
        migrations.AlterField(
            model_name='thing',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
