# Generated by Django 2.2.6 on 2019-10-13 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191013_0914'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thing',
            name='user',
        ),
    ]
